//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageAlbum
    {
        public int ID { get; set; }
        public int IDImage { get; set; }
        public int IDAlbum { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual Images Images { get; set; }
    }
}
